version: "3"

services:
    mariadb:
        image: dtrabalho17/seguro:mariadb
        container_name: MariaDB
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr

    web:
        image: dtrabalho17/seguro:dolibarr
        container_name: Dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://0.0.0.0'
            PHP_INI_DATE_TIMEZONE: 'America/sao_paulo'
        ports:
            - "80:80"
        links:
            - mariadb
